package com.nf2.sss.eneity1;

import java.util.Date;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.authorid
     *
     * @mbg.generated
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.brith
     *
     * @mbg.generated
     */
    private Date brith;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.authorid
     *
     * @return the value of author.authorid
     *
     * @mbg.generated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.authorid
     *
     * @param authorid the value for author.authorid
     *
     * @mbg.generated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.name
     *
     * @return the value of author.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.name
     *
     * @param name the value for author.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.tel
     *
     * @return the value of author.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.tel
     *
     * @param tel the value for author.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.brith
     *
     * @return the value of author.brith
     *
     * @mbg.generated
     */
    public Date getBrith() {
        return brith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.brith
     *
     * @param brith the value for author.brith
     *
     * @mbg.generated
     */
    public void setBrith(Date brith) {
        this.brith = brith;
    }
}