package com.nf2.sss.eneity1;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookid
     *
     * @mbg.generated
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbg.generated
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.authorid
     *
     * @mbg.generated
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_at
     *
     * @mbg.generated
     */
    private Date publishAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.creat_at
     *
     * @mbg.generated
     */
    private Date creatAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookid
     *
     * @return the value of book.bookid
     *
     * @mbg.generated
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookid
     *
     * @param bookid the value for book.bookid
     *
     * @mbg.generated
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbg.generated
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbg.generated
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.authorid
     *
     * @return the value of book.authorid
     *
     * @mbg.generated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.authorid
     *
     * @param authorid the value for book.authorid
     *
     * @mbg.generated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_at
     *
     * @return the value of book.publish_at
     *
     * @mbg.generated
     */
    public Date getPublishAt() {
        return publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish_at
     *
     * @param publishAt the value for book.publish_at
     *
     * @mbg.generated
     */
    public void setPublishAt(Date publishAt) {
        this.publishAt = publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.creat_at
     *
     * @return the value of book.creat_at
     *
     * @mbg.generated
     */
    public Date getCreatAt() {
        return creatAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.creat_at
     *
     * @param creatAt the value for book.creat_at
     *
     * @mbg.generated
     */
    public void setCreatAt(Date creatAt) {
        this.creatAt = creatAt;
    }
}