package com.nf2.sss.eneity1;

public class CharDom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_dom.a
     *
     * @mbg.generated
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_dom.b
     *
     * @mbg.generated
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_dom.c
     *
     * @mbg.generated
     */
    private String c;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_dom.a
     *
     * @return the value of char_dom.a
     *
     * @mbg.generated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_dom.a
     *
     * @param a the value for char_dom.a
     *
     * @mbg.generated
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_dom.b
     *
     * @return the value of char_dom.b
     *
     * @mbg.generated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_dom.b
     *
     * @param b the value for char_dom.b
     *
     * @mbg.generated
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_dom.c
     *
     * @return the value of char_dom.c
     *
     * @mbg.generated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_dom.c
     *
     * @param c the value for char_dom.c
     *
     * @mbg.generated
     */
    public void setC(String c) {
        this.c = c == null ? null : c.trim();
    }
}