package com.nf2.sss.eneity1;

import java.math.BigDecimal;

public class FdbDom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fdb_dom.a
     *
     * @mbg.generated
     */
    private Float a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fdb_dom.b
     *
     * @mbg.generated
     */
    private Double b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fdb_dom.c
     *
     * @mbg.generated
     */
    private BigDecimal c;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdb_dom.a
     *
     * @return the value of fdb_dom.a
     *
     * @mbg.generated
     */
    public Float getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdb_dom.a
     *
     * @param a the value for fdb_dom.a
     *
     * @mbg.generated
     */
    public void setA(Float a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdb_dom.b
     *
     * @return the value of fdb_dom.b
     *
     * @mbg.generated
     */
    public Double getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdb_dom.b
     *
     * @param b the value for fdb_dom.b
     *
     * @mbg.generated
     */
    public void setB(Double b) {
        this.b = b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdb_dom.c
     *
     * @return the value of fdb_dom.c
     *
     * @mbg.generated
     */
    public BigDecimal getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdb_dom.c
     *
     * @param c the value for fdb_dom.c
     *
     * @mbg.generated
     */
    public void setC(BigDecimal c) {
        this.c = c;
    }
}