package com.nf2.sss.eneity1;

public class SssAuthor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_author.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_author.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_author.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_author.id
     *
     * @return the value of sss_author.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_author.id
     *
     * @param id the value for sss_author.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_author.name
     *
     * @return the value of sss_author.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_author.name
     *
     * @param name the value for sss_author.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_author.city
     *
     * @return the value of sss_author.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_author.city
     *
     * @param city the value for sss_author.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}