package com.nf2.sss.eneity1;

public class SssBillinginfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.bid
     *
     * @mbg.generated
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.in_id
     *
     * @mbg.generated
     */
    private Integer inId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.cu_id
     *
     * @mbg.generated
     */
    private Integer cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.biaddress
     *
     * @mbg.generated
     */
    private String biaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.biCity
     *
     * @mbg.generated
     */
    private String bicity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.biCountry
     *
     * @mbg.generated
     */
    private String bicountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_billinginfo.biPostalCode
     *
     * @mbg.generated
     */
    private String bipostalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.bid
     *
     * @return the value of sss_billinginfo.bid
     *
     * @mbg.generated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.bid
     *
     * @param bid the value for sss_billinginfo.bid
     *
     * @mbg.generated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.in_id
     *
     * @return the value of sss_billinginfo.in_id
     *
     * @mbg.generated
     */
    public Integer getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.in_id
     *
     * @param inId the value for sss_billinginfo.in_id
     *
     * @mbg.generated
     */
    public void setInId(Integer inId) {
        this.inId = inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.cu_id
     *
     * @return the value of sss_billinginfo.cu_id
     *
     * @mbg.generated
     */
    public Integer getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.cu_id
     *
     * @param cuId the value for sss_billinginfo.cu_id
     *
     * @mbg.generated
     */
    public void setCuId(Integer cuId) {
        this.cuId = cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.biaddress
     *
     * @return the value of sss_billinginfo.biaddress
     *
     * @mbg.generated
     */
    public String getBiaddress() {
        return biaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.biaddress
     *
     * @param biaddress the value for sss_billinginfo.biaddress
     *
     * @mbg.generated
     */
    public void setBiaddress(String biaddress) {
        this.biaddress = biaddress == null ? null : biaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.biCity
     *
     * @return the value of sss_billinginfo.biCity
     *
     * @mbg.generated
     */
    public String getBicity() {
        return bicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.biCity
     *
     * @param bicity the value for sss_billinginfo.biCity
     *
     * @mbg.generated
     */
    public void setBicity(String bicity) {
        this.bicity = bicity == null ? null : bicity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.biCountry
     *
     * @return the value of sss_billinginfo.biCountry
     *
     * @mbg.generated
     */
    public String getBicountry() {
        return bicountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.biCountry
     *
     * @param bicountry the value for sss_billinginfo.biCountry
     *
     * @mbg.generated
     */
    public void setBicountry(String bicountry) {
        this.bicountry = bicountry == null ? null : bicountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_billinginfo.biPostalCode
     *
     * @return the value of sss_billinginfo.biPostalCode
     *
     * @mbg.generated
     */
    public String getBipostalcode() {
        return bipostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_billinginfo.biPostalCode
     *
     * @param bipostalcode the value for sss_billinginfo.biPostalCode
     *
     * @mbg.generated
     */
    public void setBipostalcode(String bipostalcode) {
        this.bipostalcode = bipostalcode == null ? null : bipostalcode.trim();
    }
}