package com.nf2.sss.eneity1;

public class TScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.subjects
     *
     * @mbg.generated
     */
    private String subjects;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_score.fraction
     *
     * @mbg.generated
     */
    private String fraction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.p_id
     *
     * @return the value of t_score.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.p_id
     *
     * @param pId the value for t_score.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.p_name
     *
     * @return the value of t_score.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.p_name
     *
     * @param pName the value for t_score.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.subjects
     *
     * @return the value of t_score.subjects
     *
     * @mbg.generated
     */
    public String getSubjects() {
        return subjects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.subjects
     *
     * @param subjects the value for t_score.subjects
     *
     * @mbg.generated
     */
    public void setSubjects(String subjects) {
        this.subjects = subjects == null ? null : subjects.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_score.fraction
     *
     * @return the value of t_score.fraction
     *
     * @mbg.generated
     */
    public String getFraction() {
        return fraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_score.fraction
     *
     * @param fraction the value for t_score.fraction
     *
     * @mbg.generated
     */
    public void setFraction(String fraction) {
        this.fraction = fraction == null ? null : fraction.trim();
    }
}