package com.nf2.sss.eneity1;

import java.util.Date;

public class XxInvoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.invoice_id
     *
     * @mbg.generated
     */
    private Integer invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.invoice_date
     *
     * @mbg.generated
     */
    private Date invoiceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.billing_address
     *
     * @mbg.generated
     */
    private String billingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.billing_city
     *
     * @mbg.generated
     */
    private String billingCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.billing_state
     *
     * @mbg.generated
     */
    private String billingState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.billing_country
     *
     * @mbg.generated
     */
    private String billingCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.billing_postalCode
     *
     * @mbg.generated
     */
    private String billingPostalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_invoice.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.invoice_id
     *
     * @return the value of xx_invoice.invoice_id
     *
     * @mbg.generated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.invoice_id
     *
     * @param invoiceId the value for xx_invoice.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.customer_id
     *
     * @return the value of xx_invoice.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.customer_id
     *
     * @param customerId the value for xx_invoice.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.invoice_date
     *
     * @return the value of xx_invoice.invoice_date
     *
     * @mbg.generated
     */
    public Date getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.invoice_date
     *
     * @param invoiceDate the value for xx_invoice.invoice_date
     *
     * @mbg.generated
     */
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.billing_address
     *
     * @return the value of xx_invoice.billing_address
     *
     * @mbg.generated
     */
    public String getBillingAddress() {
        return billingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.billing_address
     *
     * @param billingAddress the value for xx_invoice.billing_address
     *
     * @mbg.generated
     */
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress == null ? null : billingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.billing_city
     *
     * @return the value of xx_invoice.billing_city
     *
     * @mbg.generated
     */
    public String getBillingCity() {
        return billingCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.billing_city
     *
     * @param billingCity the value for xx_invoice.billing_city
     *
     * @mbg.generated
     */
    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity == null ? null : billingCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.billing_state
     *
     * @return the value of xx_invoice.billing_state
     *
     * @mbg.generated
     */
    public String getBillingState() {
        return billingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.billing_state
     *
     * @param billingState the value for xx_invoice.billing_state
     *
     * @mbg.generated
     */
    public void setBillingState(String billingState) {
        this.billingState = billingState == null ? null : billingState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.billing_country
     *
     * @return the value of xx_invoice.billing_country
     *
     * @mbg.generated
     */
    public String getBillingCountry() {
        return billingCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.billing_country
     *
     * @param billingCountry the value for xx_invoice.billing_country
     *
     * @mbg.generated
     */
    public void setBillingCountry(String billingCountry) {
        this.billingCountry = billingCountry == null ? null : billingCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.billing_postalCode
     *
     * @return the value of xx_invoice.billing_postalCode
     *
     * @mbg.generated
     */
    public String getBillingPostalcode() {
        return billingPostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.billing_postalCode
     *
     * @param billingPostalcode the value for xx_invoice.billing_postalCode
     *
     * @mbg.generated
     */
    public void setBillingPostalcode(String billingPostalcode) {
        this.billingPostalcode = billingPostalcode == null ? null : billingPostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_invoice.total
     *
     * @return the value of xx_invoice.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_invoice.total
     *
     * @param total the value for xx_invoice.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }
}