package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.CharDom;
import java.util.List;

public interface CharDomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_dom
     *
     * @mbg.generated
     */
    int insert(CharDom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_dom
     *
     * @mbg.generated
     */
    List<CharDom> selectAll();
}