package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.FdbDom;
import java.util.List;

public interface FdbDomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdb_dom
     *
     * @mbg.generated
     */
    int insert(FdbDom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdb_dom
     *
     * @mbg.generated
     */
    List<FdbDom> selectAll();
}