package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.SssAuthor;
import java.util.List;

public interface SssAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_author
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_author
     *
     * @mbg.generated
     */
    int insert(SssAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_author
     *
     * @mbg.generated
     */
    SssAuthor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_author
     *
     * @mbg.generated
     */
    List<SssAuthor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_author
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssAuthor record);
}