package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.SssComment;
import java.util.List;

public interface SssCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_comment
     *
     * @mbg.generated
     */
    int insert(SssComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_comment
     *
     * @mbg.generated
     */
    SssComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_comment
     *
     * @mbg.generated
     */
    List<SssComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssComment record);
}