package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.XxCustomer;
import java.util.List;

public interface XxCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_customer
     *
     * @mbg.generated
     */
    int insert(XxCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_customer
     *
     * @mbg.generated
     */
    XxCustomer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_customer
     *
     * @mbg.generated
     */
    List<XxCustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XxCustomer record);
}