package com.nf2.sss.dao1;

import com.nf2.sss.eneity1.XxInvoice;
import java.util.List;

public interface XxInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_invoice
     *
     * @mbg.generated
     */
    int insert(XxInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_invoice
     *
     * @mbg.generated
     */
    XxInvoice selectByPrimaryKey(Integer invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_invoice
     *
     * @mbg.generated
     */
    List<XxInvoice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XxInvoice record);
}